name = "jujutracer"
uuid = "6725bcfb-d8cf-49c6-9670-0c78602db570"
authors =[
    "Michele Boldini <michele.boldini@studenti.unimi.it>",
    "Giovanni Galafassi <giovanni.galafassi@studenti.unimi.it>",
    "Lonardoni Stefano <stefano.lonardoni1@studenti.unimi.it>"
]
version = "0.1.0"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
ColorTypes = "0.12.0"
Colors = "0.13.0"
Test = "1.9.2"
