name: Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags: '*'
    paths:
      - 'docs/src/**'
      - 'src/**'
      - 'main.jl'

jobs:
  build:
    permissions:
      actions: write
      contents: write
      pull-requests: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper versioning
      
      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.11'
      
      - name: Cache Julia packages
        uses: julia-actions/cache@v2
      
      - name: Build and deploy documentation
        uses: julia-actions/julia-docdeploy@latest
        env:
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}