name: Test on Pull Request

on:
  # so it runs even if hte pr is not mergeable
  pull_request_target:
    paths:
      - 'src/**'
      - 'test/**'
      - 'Project.toml'

permissions:
  actions: write
  contents: read

jobs:
  # Job to test on Ubuntu for all pull requests
  draft-tests:
    if: github.event.pull_request.draft == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: 1.11

      - name: Cache Julia packages
        uses: julia-actions/cache@v2

      - name: Build package
        uses: julia-actions/julia-buildpkg@v1

      - name: Run tests
        uses: julia-actions/julia-runtest@v1
        with:
          annotate: true

  # Job to test on all platforms when the pull request is not a draft
  pre-merge-tests:
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: 1.11

      - name: Cache Julia packages
        uses: julia-actions/cache@v2

      - name: Build package
        uses: julia-actions/julia-buildpkg@v1

      - name: Run tests
        uses: julia-actions/julia-runtest@v1
        with:
          annotate: true