name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  actions: write
  contents: read

jobs:
    test:
        strategy:
          matrix:
            julia-version: [1.11.3, 1.11.4, 'lts', 'stable']
            julia-arch: [x64, x86]
            os: [ubuntu-latest, windows-latest, macOS-latest]
            exclude:
              - os: windows-latest
                julia-version: 1.11.3 
        runs-on: ${{ matrix.os }}

        steps:
          - name: Checkout code
            uses: actions/checkout@v2
            
          - name: Set up Julia
            uses: julia-actions/setup-julia@v1
            with:
              version: ${{ matrix.julia-version }}
            
          - name: Cache Julia packages
            uses: julia-actions/cache@v2
            
          - name: Build package
            uses: julia-actions/julia-buildpkg@v1
            
          - name: Run tests
            uses: julia-actions/julia-runtest@v1 
            with:
              annotate: true
