name: Validate ready-for-merge Label

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited

permissions:
  contents: write
  pull-requests: write

jobs:
  validate-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Ready-for-Merge Label
        uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 1
          labels: "ready-for-merge"
          add_comment: true
          message: "This PR is missing the 'ready-for-merge' label. Please add it to trigger the pre-merge tests."
